import turtle
window = turtle.Screen()
jairo = turtle.Turtle()
jairo.forward(50)
jairo.left(90)
jairo.forward(50)
jairo.left(90)
jairo.forward(50)
jairo.left(90)
jairo.forward(50)
jairo.left(90)
jairo.forward(50)
jairo.left(90)

turtle.mainloop()
